last_change = 2026-09-10T18:36:44.775919Z
addr = 0x367450
size = 0xa6
name = "CEngineServiceMgr_OnFrameRenderingFinished"
type = "long long"

[header]
name = "CEngineServiceMgr_OnFrameRenderingFinished"
addr = 0x367450
type = "long long"

[header.args]
