last_change = 2026-09-10T18:36:44.775941Z
addr = 0x36c6c0
size = 0xdc
name = "CEngineServiceMgr_UnregisterEngineService"
type = "unsigned long long *"

[header]
name = "CEngineServiceMgr_UnregisterEngineService"
addr = 0x36c6c0
type = "unsigned long long *"

[header.args]
