last_change = 2026-09-11T03:32:58.380857Z
addr = 0x36cc40
size = 0x217
name = "CEngineServiceMgr_RegisterLoopMode"

[header]
name = "CEngineServiceMgr_RegisterLoopMode"
addr = 0x36cc40

[header.args]
