last_change = 2026-09-10T18:36:46.677972Z
addr = 0x366810
size = 0x23
name = "CEngineServiceMgr_GetActiveLoopClientServerMode"
type = "long long"

[header]
name = "CEngineServiceMgr_GetActiveLoopClientServerMode"
addr = 0x366810
type = "long long"

[header.args]
