last_change = 2026-09-10T18:36:46.695376Z
addr = 0x366de0
size = 0xb1
name = "CEngineServiceMgr_UnregisterLoopMode"
type = "unsigned long long *"

[header]
name = "CEngineServiceMgr_UnregisterLoopMode"
addr = 0x366de0
type = "unsigned long long *"

[header.args]
