last_change = 2026-09-11T03:32:58.380798Z
addr = 0x366810
size = 0x23
name = "CEngineServiceMgr_GetActiveLoopClientServerMode"

[header]
name = "CEngineServiceMgr_GetActiveLoopClientServerMode"
addr = 0x366810

[header.args]
