last_change = 2026-09-11T03:32:58.380870Z
addr = 0x379600
size = 0x275
name = "CLoopTypeBase_LoadDependentServices"

[header]
name = "CLoopTypeBase_LoadDependentServices"
addr = 0x379600

[header.args]
