last_change = 2026-09-11T03:32:58.380897Z
addr = 0x37c880
size = 0x42a
name = "CLoopTypeClientServer_AllocateLoopMode"

[header]
name = "CLoopTypeClientServer_AllocateLoopMode"
addr = 0x37c880

[header.args]
