last_change = 2026-09-10T18:36:44.775977Z
addr = 0x37bb60
size = 0x1c7
name = "CLoopTypeClientServerService_OnLoopActivate"
type = "void"

[header]
name = "CLoopTypeClientServerService_OnLoopActivate"
addr = 0x37bb60
type = "void"

[header.args]
