last_change = 2026-09-11T03:32:58.380875Z
addr = 0x3798c0
size = 0x2bd
name = "CLoopTypeClientSimple_ActivateEngineServices"

[header]
name = "CLoopTypeClientSimple_ActivateEngineServices"
addr = 0x3798c0

[header.args]
