last_change = 2026-09-10T18:36:44.775956Z
addr = 0x379600
size = 0x275
name = "CLoopTypeBase_LoadDependentServices"
type = "long long"

[header]
name = "CLoopTypeBase_LoadDependentServices"
addr = 0x379600
type = "long long"

[header.args]
