last_change = 2026-09-10T18:36:44.775962Z
addr = 0x3798c0
size = 0x2bd
name = "CLoopTypeClientSimple_ActivateEngineServices"
type = "long long"

[header]
name = "CLoopTypeClientSimple_ActivateEngineServices"
addr = 0x3798c0
type = "long long"

[header.args]
