last_change = 2026-09-10T18:36:44.775997Z
addr = 0x3802b0
size = 0x866
name = "CLoopTypeClientServer_OutputListeners"
type = "unsigned long long"

[header]
name = "CLoopTypeClientServer_OutputListeners"
addr = 0x3802b0
type = "unsigned long long"

[header.args]
