last_change = 2026-09-11T03:32:58.380913Z
addr = 0x3802b0
size = 0x866
name = "CLoopTypeClientServer_OutputListeners"

[header]
name = "CLoopTypeClientServer_OutputListeners"
addr = 0x3802b0

[header.args]
