last_change = 2026-09-11T03:32:58.380917Z
addr = 0x3873a0
size = 0x70f
name = "CLoopTypeClientServer_LoopTypeInit"

[header]
name = "CLoopTypeClientServer_LoopTypeInit"
addr = 0x3873a0

[header.args]
