last_change = 2026-09-11T03:32:58.380944Z
addr = 0x39a3c0
size = 0xcb
name = "CLoopTypeSimpleService_OnLoopActivate"

[header]
name = "CLoopTypeSimpleService_OnLoopActivate"
addr = 0x39a3c0

[header.args]
