last_change = 2026-09-10T18:36:46.797074Z
addr = 0x390b50
size = 0x132
name = "CLoopTypeClientServer_ActivateLoop"
type = "long long"

[header]
name = "CLoopTypeClientServer_ActivateLoop"
addr = 0x390b50
type = "long long"

[header.args]
