last_change = 2026-09-11T03:32:58.380962Z
addr = 0x3c7ba0
size = 0x7a
name = "CGameResourceService_DescribeContents"

[header]
name = "CGameResourceService_DescribeContents"
addr = 0x3c7ba0

[header.args]
