last_change = 2026-09-10T18:36:46.843923Z
addr = 0x3c9120
size = 0x138
name = "CGameResourceService_BuildResourceManifest"
type = "long long"

[header]
name = "CGameResourceService_BuildResourceManifest"
addr = 0x3c9120
type = "long long"

[header.args]
