last_change = 2026-09-11T03:32:58.380990Z
addr = 0x3ca310
size = 0x282
name = "CGameResourceService_LoadGameResourceManifestNamed"

[header]
name = "CGameResourceService_LoadGameResourceManifestNamed"
addr = 0x3ca310

[header.args]
