last_change = 2026-09-11T03:32:58.380985Z
addr = 0x3ca130
size = 0x1da
name = "CGameResourceService_LoadGameResourceManifest_IEntityResourceManifest"

[header]
name = "CGameResourceService_LoadGameResourceManifest_IEntityResourceManifest"
addr = 0x3ca130

[header.args]
