last_change = 2026-09-11T03:32:58.381001Z
addr = 0x3d0fe0
size = 0x161
name = "CGameResourceService_AppendToGameResourceManifest"

[header]
name = "CGameResourceService_AppendToGameResourceManifest"
addr = 0x3d0fe0

[header.args]
