last_change = 2026-09-10T18:36:44.776116Z
addr = 0x3ef580
size = 0xcd7
name = "CInputService_ProcessCommand"
type = "long long"

[header]
name = "CInputService_ProcessCommand"
addr = 0x3ef580
type = "long long"

[header.args]
