last_change = 2026-09-10T06:53:36.475183Z
addr = 0x3fa480
size = 0x19
name = "CNetworkServerService_OnServerEndSimulate"

[header]
name = "CNetworkServerService_OnServerEndSimulate"
addr = 0x3fa480

[header.args]
