last_change = 2026-09-11T03:32:58.381065Z
addr = 0x400a50
size = 0x8c
name = "CNetworkServerService_OnKickByIdHLTV"

[header]
name = "CNetworkServerService_OnKickByIdHLTV"
addr = 0x400a50

[header.args]
