last_change = 2026-09-10T18:36:46.956584Z
addr = 0x404920
size = 0xbb
name = "CNetworkServerService_OnServerProcessNetworking"
type = "long long"

[header]
name = "CNetworkServerService_OnServerProcessNetworking"
addr = 0x404920
type = "long long"

[header.args]
