last_change = 2026-09-10T06:53:36.475208Z
addr = 0x40a850
size = 0xc9
name = "CNetworkServerService_GetServerSerializersCRC"

[header]
name = "CNetworkServerService_GetServerSerializersCRC"
addr = 0x40a850

[header.args]
