last_change = 2026-09-11T03:32:58.381107Z
addr = 0x409620
size = 0x111
name = "CNetworkServerService_AddServerPrerequisites"

[header]
name = "CNetworkServerService_AddServerPrerequisites"
addr = 0x409620

[header.args]
