last_change = 2026-09-11T03:32:58.381137Z
addr = 0x416c80
size = 0x207
name = "CNetworkServerService_DisconnectGameNow"

[header]
name = "CNetworkServerService_DisconnectGameNow"
addr = 0x416c80

[header.args]
