last_change = 2026-09-10T18:36:44.776256Z
addr = 0x417180
size = 0x8
name = "CNetworkClientService_GetDisconnectReason"
type = "const char *"

[header]
name = "CNetworkClientService_GetDisconnectReason"
addr = 0x417180
type = "const char *"

[header.args]
