last_change = 2026-09-11T03:32:58.381142Z
addr = 0x417180
size = 0x8
name = "CNetworkClientService_GetDisconnectReason"

[header]
name = "CNetworkClientService_GetDisconnectReason"
addr = 0x417180

[header.args]
