last_change = 2026-09-11T03:32:58.381211Z
addr = 0x42d080
size = 0x39
name = "CNetworkClientService_IsPutInServer"

[header]
name = "CNetworkClientService_IsPutInServer"
addr = 0x42d080

[header.args]
