last_change = 2026-09-10T18:36:44.776330Z
addr = 0x42d170
size = 0x21
name = "CNetworkClientService_SendStringCmd"
type = "void"

[header]
name = "CNetworkClientService_SendStringCmd"
addr = 0x42d170
type = "void"

[header.args]
