last_change = 2026-09-10T18:36:44.776301Z
addr = 0x42c310
size = 0x107
name = "CNetworkClientService_DisconnectGameNow"
type = "void"

[header]
name = "CNetworkClientService_DisconnectGameNow"
addr = 0x42c310
type = "void"

[header.args]
