last_change = 2026-09-11T03:32:58.381197Z
addr = 0x42ca20
size = 0x2f3
name = "CNetworkClientService_PrintConnectionStatus"

[header]
name = "CNetworkClientService_PrintConnectionStatus"
addr = 0x42ca20

[header.args]
