last_change = 2026-09-10T18:36:44.776334Z
addr = 0x42d1a0
size = 0x6a
name = "CNetworkClientService_SplitScreenConnect"
type = "long long"

[header]
name = "CNetworkClientService_SplitScreenConnect"
addr = 0x42d1a0
type = "long long"

[header.args]
