last_change = 2026-09-11T03:32:58.381182Z
addr = 0x4288b0
size = 0x147
name = "CNetworkClientService_AllocateRemoteConnectionClient"

[header]
name = "CNetworkClientService_AllocateRemoteConnectionClient"
addr = 0x4288b0

[header.args]
