last_change = 2026-09-10T18:36:44.776310Z
addr = 0x42ca20
size = 0x2f3
name = "CNetworkClientService_PrintConnectionStatus"
type = "long long"

[header]
name = "CNetworkClientService_PrintConnectionStatus"
addr = 0x42ca20
type = "long long"

[header.args]
