last_change = 2026-09-10T18:36:44.776315Z
addr = 0x42cd20
size = 0x2a8
name = "CNetworkClientService_OnStatus"
type = "void"

[header]
name = "CNetworkClientService_OnStatus"
addr = 0x42cd20
type = "void"

[header.args]
