last_change = 2026-09-10T18:36:44.776286Z
addr = 0x421c40
size = 0x107
name = "CNetworkClientService_AddClientPrerequisites"
type = "long long"

[header]
name = "CNetworkClientService_AddClientPrerequisites"
addr = 0x421c40
type = "long long"

[header.args]
