last_change = 2026-09-10T18:36:44.776325Z
addr = 0x42d080
size = 0x39
name = "CNetworkClientService_IsPutInServer"
type = "bool"

[header]
name = "CNetworkClientService_IsPutInServer"
addr = 0x42d080
type = "bool"

[header.args]
