last_change = 2026-09-10T18:36:44.776306Z
addr = 0x42c750
size = 0x117
name = "CNetworkClientService_Shutdown"
type = "long long"

[header]
name = "CNetworkClientService_Shutdown"
addr = 0x42c750
type = "long long"

[header.args]
