last_change = 2026-09-10T18:36:47.122650Z
addr = 0x4360c0
size = 0x3cd
name = "CRenderService_OnClientOutput"
type = "long long"

[header]
name = "CRenderService_OnClientOutput"
addr = 0x4360c0
type = "long long"

[header.args]
