last_change = 2026-09-10T18:36:44.776363Z
addr = 0x4499c0
size = 0x147
name = "CSplitScreenService_AddSplitScreenUser"
type = "long long"

[header]
name = "CSplitScreenService_AddSplitScreenUser"
addr = 0x4499c0
type = "long long"

[header.args]
