last_change = 2026-09-11T03:32:58.381275Z
addr = 0x49c380
size = 0x239
name = "CNetworkGameClient_RecordEntityBandwidth"

[header]
name = "CNetworkGameClient_RecordEntityBandwidth"
addr = 0x49c380

[header.args]
