last_change = 2026-09-10T18:36:44.776389Z
addr = 0x492070
size = 0x1a5
name = "Demo_PauseAtServerTick_CommandHandler"
type = "void *"

[header]
name = "Demo_PauseAtServerTick_CommandHandler"
addr = 0x492070
type = "void *"

[header.args]
