last_change = 2026-09-11T03:32:58.381280Z
addr = 0x4a0700
size = 0xc31
name = "CNetworkGameClient_ProcessPacketEntities"

[header]
name = "CNetworkGameClient_ProcessPacketEntities"
addr = 0x4a0700

[header.args]
