last_change = 2026-09-10T18:36:44.776451Z
addr = 0x4bf440
size = 0x268
name = "CNetworkGameClientBase_ProcessSplitScreen"
type = "long long"

[header]
name = "CNetworkGameClientBase_ProcessSplitScreen"
addr = 0x4bf440
type = "long long"

[header.args]
