last_change = 2026-09-11T03:32:58.381300Z
addr = 0x4b6800
size = 0x16
name = "CNetworkGameClientBase_ProcessSpawnGroup_ManifestUpdate"

[header]
name = "CNetworkGameClientBase_ProcessSpawnGroup_ManifestUpdate"
addr = 0x4b6800

[header.args]
