last_change = 2026-09-11T03:32:58.381333Z
addr = 0x4c9f60
size = 0x450
name = "CNetworkGameClientBase_DisconnectGame"

[header]
name = "CNetworkGameClientBase_DisconnectGame"
addr = 0x4c9f60

[header.args]
