last_change = 2026-09-10T06:53:36.475306Z
addr = 0x4cf780
size = 0x314
name = "CNetworkGameClientBase_FinishChangeLevel"

[header]
name = "CNetworkGameClientBase_FinishChangeLevel"
addr = 0x4cf780

[header.args]
