last_change = 2026-09-10T18:36:44.776456Z
addr = 0x4c9f60
size = 0x450
name = "CNetworkGameClientBase_DisconnectGame"
type = "void"

[header]
name = "CNetworkGameClientBase_DisconnectGame"
addr = 0x4c9f60
type = "void"

[header.args]
