last_change = 2026-09-11T03:32:58.381357Z
addr = 0x4d2820
size = 0xca
name = "CNetworkGameClient_HookClientStringTable"

[header]
name = "CNetworkGameClient_HookClientStringTable"
addr = 0x4d2820

[header.args]
