last_change = 2026-09-11T03:32:58.381377Z
addr = 0x4db820
size = 0x15
name = "CMsgSource2NetworkFlowQuality_PrintStats"

[header]
name = "CMsgSource2NetworkFlowQuality_PrintStats"
addr = 0x4db820

[header.args]
