last_change = 2026-09-10T18:36:44.776537Z
addr = 0x4e7860
size = 0x1a9
name = "CNetworkGameClient_ProcessServerInfo"
type = "long long"

[header]
name = "CNetworkGameClient_ProcessServerInfo"
addr = 0x4e7860
type = "long long"

[header.args]
