last_change = 2026-09-10T18:36:44.776565Z
addr = 0x4e9480
size = 0x2a
name = "CEngineClient_DumpNetStats"
type = "long long (__fastcall *)(__int128 *, __int128 *, long long)"

[header]
name = "CEngineClient_DumpNetStats"
addr = 0x4e9480
type = "long long (__fastcall *)(__int128 *, __int128 *, long long)"

[header.args]
