last_change = 2026-09-10T06:53:36.475337Z
addr = 0x4e6fb0
size = 0x3ce
name = "CNetworkGameClient_ProcessClassInfo"

[header]
name = "CNetworkGameClient_ProcessClassInfo"
addr = 0x4e6fb0

[header.args]
