last_change = 2026-09-10T18:36:44.776635Z
addr = 0x4f6cd0
size = 0x225
name = "CNetworkGameServerBase_BroadcastEntityVoice"
type = "long long"

[header]
name = "CNetworkGameServerBase_BroadcastEntityVoice"
addr = 0x4f6cd0
type = "long long"

[header.args]
