last_change = 2026-09-10T18:36:44.776610Z
addr = 0x4f5b40
size = 0x11f
name = "CNetworkGameServerBase_ServerProcessNetworking"
type = "void"

[header]
name = "CNetworkGameServerBase_ServerProcessNetworking"
addr = 0x4f5b40
type = "void"

[header.args]
