last_change = 2026-09-10T18:36:44.776585Z
addr = 0x4f4a40
size = 0x9
name = "CNetworkGameServerBase_GetTimescale"
type = "float"

[header]
name = "CNetworkGameServerBase_GetTimescale"
addr = 0x4f4a40
type = "float"

[header.args]
