last_change = 2026-09-10T18:36:44.776630Z
addr = 0x4f6940
size = 0x389
name = "CNetworkGameServerBase_GetClassBaseline"
type = "bool"

[header]
name = "CNetworkGameServerBase_GetClassBaseline"
addr = 0x4f6940
type = "bool"

[header.args]
