last_change = 2026-09-11T03:32:58.381458Z
addr = 0x4f4a50
size = 0x8
name = "CNetworkGameServerBase_IsChangelevelPending"

[header]
name = "CNetworkGameServerBase_IsChangelevelPending"
addr = 0x4f4a50

[header.args]
