last_change = 2026-09-11T03:32:58.381487Z
addr = 0x4f63b0
size = 0x3de
name = "CNetworkGameServerBase_BroadcastMessage"

[header]
name = "CNetworkGameServerBase_BroadcastMessage"
addr = 0x4f63b0

[header.args]
