last_change = 2026-09-10T18:36:44.776753Z
addr = 0x50e740
size = 0x216
name = "CNetworkGameServerBase_AsyncUnloadSpawnGroup"
type = "void"

[header]
name = "CNetworkGameServerBase_AsyncUnloadSpawnGroup"
addr = 0x50e740
type = "void"

[header.args]
