last_change = 2026-09-11T03:32:58.381590Z
addr = 0x507d00
size = 0x2341
name = "CNetworkGameServerBase_ConnectClient"

[header]
name = "CNetworkGameServerBase_ConnectClient"
addr = 0x507d00

[header.args]
