last_change = 2026-09-11T03:32:58.381649Z
addr = 0x5133a0
size = 0x59
name = "CNetworkGameServer_GetPlayerNetworkIDString"

[header]
name = "CNetworkGameServer_GetPlayerNetworkIDString"
addr = 0x5133a0

[header.args]
