last_change = 2026-09-10T18:36:44.776920Z
addr = 0x51a400
size = 0x6c
name = "CEngineServer_DumpNetStats"
type = "long long"

[header]
name = "CEngineServer_DumpNetStats"
addr = 0x51a400
type = "long long"

[header.args]
