last_change = 2026-09-10T18:36:44.776871Z
addr = 0x519570
size = 0x10f
name = "CEngineServer_GetClientSteamID"
type = "long long"

[header]
name = "CEngineServer_GetClientSteamID"
addr = 0x519570
type = "long long"

[header.args]
