last_change = 2026-09-10T18:36:44.776939Z
addr = 0x51a5d0
size = 0x5
name = "CEngineServer_GetSteamUniverse"
type = "long long"

[header]
name = "CEngineServer_GetSteamUniverse"
addr = 0x51a5d0
type = "long long"

[header.args]
