last_change = 2026-09-10T06:53:36.475516Z
addr = 0x51bd10
size = 0x33b
name = "CEngineServer_ClientCommandKeyValues"

[header]
name = "CEngineServer_ClientCommandKeyValues"
addr = 0x51bd10

[header.args]
