last_change = 2026-09-10T18:36:44.776964Z
addr = 0x51c0b0
size = 0x186
name = "CNetworkGameServer_ChangeLevel"
type = "long long"

[header]
name = "CNetworkGameServer_ChangeLevel"
addr = 0x51c0b0
type = "long long"

[header.args]
