last_change = 2026-09-10T18:36:47.634946Z
addr = 0x518c20
size = 0xb0
name = "CNetworkGameServer_Shutdown"
type = "long long"

[header]
name = "CNetworkGameServer_Shutdown"
addr = 0x518c20
type = "long long"

[header.args]
