last_change = 2026-09-11T03:32:58.381822Z
addr = 0x51bd10
size = 0x33b
name = "CEngineServer_ClientCommandKeyValues"

[header]
name = "CEngineServer_ClientCommandKeyValues"
addr = 0x51bd10

[header.args]
