last_change = 2026-09-10T18:36:44.776835Z
addr = 0x518ae0
size = 0x131
name = "CNetworkGameServerBase_SetMaxClients"
type = "long long"

[header]
name = "CNetworkGameServerBase_SetMaxClients"
addr = 0x518ae0
type = "long long"

[header.args]
