last_change = 2026-09-10T18:36:47.826025Z
addr = 0x527220
size = 0x106
name = "CServerSideClientBase_SetConVarUserInfo"
type = "long long"

[header]
name = "CServerSideClientBase_SetConVarUserInfo"
addr = 0x527220
type = "long long"

[header.args]
