last_change = 2026-09-10T06:53:36.475532Z
addr = 0x524d90
size = 0x1cf
name = "CServerSideClientBase_ProcessClientInfo"

[header]
name = "CServerSideClientBase_ProcessClientInfo"
addr = 0x524d90

[header.args]
