last_change = 2026-09-10T18:36:44.777033Z
addr = 0x529ff0
size = 0x1c9
name = "CServerSideClientBase_ProcessStringCmd"
type = "long long"

[header]
name = "CServerSideClientBase_ProcessStringCmd"
addr = 0x529ff0
type = "long long"

[header.args]
