last_change = 2026-09-10T18:36:44.776994Z
addr = 0x524c30
size = 0x152
name = "CServerSideClientBase_ProcessTick"
type = "long long"

[header]
name = "CServerSideClientBase_ProcessTick"
addr = 0x524c30
type = "long long"

[header.args]
