last_change = 2026-09-10T18:36:44.777068Z
addr = 0x537990
size = 0x21d
name = "CServerSideClient_ctor"
type = "long long"

[header]
name = "CServerSideClient_ctor"
addr = 0x537990
type = "long long"

[header.args]
