last_change = 2026-09-10T18:36:44.777078Z
addr = 0x53de50
size = 0x60a
name = "CServerSideClient_ExecuteStringCommand"
type = "long long"

[header]
name = "CServerSideClient_ExecuteStringCommand"
addr = 0x53de50
type = "long long"

[header.args]
