last_change = 2026-09-11T03:32:58.382003Z
addr = 0x57a930
size = 0x276
name = "CSteam3Server_SendUpdatedServerDetails"

[header]
name = "CSteam3Server_SendUpdatedServerDetails"
addr = 0x57a930

[header.args]
