last_change = 2026-09-11T03:32:58.381997Z
addr = 0x57a3f0
size = 0x29c
name = "CSteam3ServerS1_ShutdownGameServer"

[header]
name = "CSteam3ServerS1_ShutdownGameServer"
addr = 0x57a3f0

[header.args]
