last_change = 2026-09-10T06:53:36.475574Z
addr = 0x57a930
size = 0x276
name = "CSteam3Server_SendUpdatedServerDetails"

[header]
name = "CSteam3Server_SendUpdatedServerDetails"
addr = 0x57a930

[header.args]
