last_change = 2026-09-10T18:36:47.929306Z
addr = 0x57b020
size = 0x47d
name = "CSteam3ServerS1_InitGameServer"
type = "long long"

[header]
name = "CSteam3ServerS1_InitGameServer"
addr = 0x57b020
type = "long long"

[header.args]
