last_change = 2026-09-10T18:36:47.936317Z
addr = 0x581f50
size = 0x2a
name = "CEngineSoundServices_ShouldSuppressNonUISounds"

[header]
name = "CEngineSoundServices_ShouldSuppressNonUISounds"
addr = 0x581f50

[header.args]
