last_change = 2026-09-11T03:32:58.382026Z
addr = 0x58b2b0
size = 0x54
name = "CInputService_IsClientOnlyCommandAllowed"

[header]
name = "CInputService_IsClientOnlyCommandAllowed"
addr = 0x58b2b0

[header.args]
