last_change = 2026-09-10T18:36:47.956966Z
addr = 0x5996f0
size = 0xeda
name = "CNetworkStringTableClient_ParseUpdate"
type = "long long"

[header]
name = "CNetworkStringTableClient_ParseUpdate"
addr = 0x5996f0
type = "long long"

[header.args]
